services:
  db:
    image: mysql:lts
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # change in production
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: