name: ppurio-service

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./node-backend
    ports:
      - "3000:3000"
    working_dir: /app
    
    # To be removed in production
    env_file:
      - "node-backend/.env"
    
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: