name: Assign member to issue and add to project

on:
  issues:
    types: [opened]

jobs:
  auto-assign-and-add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.AUTO_ASSIGN_PAT }}
          teams: frontend, backend
          numOfAssignee: 2
          allowSelfAssign: true
          abortIfPreviousAssignees: true
      - name: 'Add issue to project'
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/hansung-taeyang/projects/3
          github-token: ${{ secrets.AUTO_ASSIGN_PAT }}
          label: feature

  